services:
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  redisdb:
    image: redis
  pgadmin:
    image: elestio/pgadmin

  catalogapi:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: Services/Catalog/CatalogAPI/Dockerfile

  basketapi:
    image: ${DOCKER_REGISTRY-}basketapi
    build:
      context: .
      dockerfile: Services/Basket/BasketAPI/Dockerfile

  discountgrpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/DiscountGRPC/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:



        


